### PR TITLE
[WIP] Advanced python tutorials

### PR DESCRIPTION
**Pull request by 36000**

### CODE REVIEW

**Comment by arokem** [comment]
Looks great! Would you mind moving this into a folder called "kruper-python"? It will help keep things organized if each lesson has its materials enclosed in its own folder. Thanks!

**Comment by arokem** [comment]
Merging for now. Please feel free to make adjustments and push directly to `main`. 

The hub is set up to pull updates from main into users' home directories.

**Comment by 36000** [comment]
Sounds good, but can I get permission to push to main?

**Comment by arokem** [comment]
Granted!

**Pull request merged**
